<?php
	$shortcodes = array(
		array(
			'name'		=>	 	__( 'Register Agent', 'real-estate-manager' ),
			'base'		=>		'rem_register_agent',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
    		'description'	=>	__( 'Renders a form to register new agent', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_register_agent'),
		),
		array(
			'name'		=>	 	__( 'Edit Agent Profile', 'real-estate-manager' ),
			'base'		=>		'rem_agent_edit',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
    		'description'	=>	__( 'Renders a form to edit logged in agent\'s profile', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_agent_edit'),
		),
		array(
			'name'		=>	 	__( 'Login Agent', 'real-estate-manager' ),
			'base'		=>		'rem_agent_login',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders an AJAX based login form', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_agent_login'),
		),
		array(
			'name'		=>	 	__( 'Create Property', 'real-estate-manager' ),
			'base'		=>		'rem_create_property',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders a form to create property', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_create_property'),
		),
		array(
			'name'		=>	 	__( 'List Agents', 'real-estate-manager' ),
			'base'		=>		'rem_list_agents',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays list of agents', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_list_agents'),
		),
		array(
			'name'		=>	 	__( 'Edit Property', 'real-estate-manager' ),
			'base'		=>		'rem_edit_property',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders a form to edit property', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_edit_property'),
		),
		array(
			'name'		=>	 	__( 'Single Property', 'real-estate-manager' ),
			'base'		=>		'rem_property',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Display a single property', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_property'),
		),
		array(
			'name'		=>	 	__( 'List Properties', 'real-estate-manager' ),
			'base'		=>		'rem_list_properties',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays properties according to the settings', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_list_properties'),
		),
		array(
			'name'		=>	 	__( 'My Properties', 'real-estate-manager' ),
			'base'		=>		'rem_my_properties',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays properties of current logged in agent', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_my_properties'),
		),
		array(
			'name'		=>	 	__( 'Agent Profile', 'real-estate-manager' ),
			'base'		=>		'rem_agent_profile',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays profile of specific agent', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_agent_profile'),
		),
		array(
			'name'		=>	 	__( 'My Profile', 'real-estate-manager' ),
			'base'		=>		'rem_my_profile',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays profile of logged in agent', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_my_profile'),
		),
		array(
			'name'		=>	 	__( 'Search Results', 'real-estate-manager' ),
			'base'		=>		'rem_search_results',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays search results if searched from widget', 'real-estate-manager' ),
			'show_settings_on_create' => false,
		),
		array(
			'name'		=>	 	__( 'Properties Map', 'real-estate-manager' ),
			'base'		=>		'rem_maps',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays properties on a large map', 'real-estate-manager' ),
			'params'	=> rem_page_builder_fields('rem_maps'),
		),
		array(
			'name'		=>	 	__( 'Search Property', 'real-estate-manager' ),
			'base'		=>		'rem_search_property',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders a form to search properties via AJAX', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_search_property')
		),
		array(
			'name'		=>	 	__( 'Carousel Slider', 'real-estate-manager' ),
			'base'		=>		'rem_carousel',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders responsive carousel of properties', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_carousel')
		),
		array(
			'name'		=>	 	__( 'Inline Search Field', 'real-estate-manager' ),
			'base'		=>		'rem_simple_search',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Renders simple search form', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_simple_search')
		),
		array(
			'name'		=>	 	__( 'Logout Button', 'real-estate-manager' ),
			'base'		=>		'rem_agent_logout',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Displays a logout button', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_agent_logout')
		),
		array(
			'name'		=>	 	__( 'Manage Properties', 'real-estate-manager' ),
			'base'		=>		'rem_manage_properties',
			'category'	=>		__( 'Real Estate Manager', 'real-estate-manager' ),
			'icon' 		=> REM_URL.'/assets/images/icon.png',
			'description'	=>	__( 'Manage all properties (for admins)', 'real-estate-manager' ),
			'params'	=>		rem_page_builder_fields('rem_manage_properties')
		),
	);
?>